const shareFromMax = (items = []) => {
  const maxValue = items[0]?.bookings || 0;
  return items.map((item) => ({
    ...item,
    share: maxValue ? Math.round((item.bookings / maxValue) * 100) : 0,
  }));
};

export const mockClientDashboard = {
  summary: {
    activeProviders: 3,
    ongoingProjects: 2,
    totalSpent: 18450,
    upcomingMeetings: 3,
  },
  overview30d: [
    { label: "12 Mar", bookings: 1, spend: 2200 },
    { label: "19 Mar", bookings: 2, spend: 4800 },
    { label: "26 Mar", bookings: 1, spend: 3200 },
    { label: "2 Apr", bookings: 2, spend: 5100 },
    { label: "9 Apr", bookings: 1, spend: 3150 },
  ],
  overview6m: [
    { label: "Nov", bookings: 1, spend: 1800 },
    { label: "Dec", bookings: 2, spend: 4200 },
    { label: "Jan", bookings: 2, spend: 5700 },
    { label: "Feb", bookings: 1, spend: 2900 },
    { label: "Mar", bookings: 3, spend: 8600 },
    { label: "Apr", bookings: 2, spend: 5400 },
  ],
  taskOverview: [
    {
      id: "mock-client-task-1",
      providerName: "Riya Sharma",
      serviceTitle: "Deep Cleaning",
      status: "accepted",
      bookingDate: "2026-04-10T10:30:00.000Z",
      timeSlot: "4:30 PM",
      amount: 3200,
      createdAt: "2026-04-09T08:10:00.000Z",
    },
    {
      id: "mock-client-task-2",
      providerName: "Kabir Patel",
      serviceTitle: "AC Maintenance",
      status: "pending",
      bookingDate: "2026-04-12T07:30:00.000Z",
      timeSlot: "1:00 PM",
      amount: 1850,
      createdAt: "2026-04-08T13:45:00.000Z",
    },
  ],
  recentProviders: [
    {
      id: "mock-client-provider-1",
      providerName: "Riya Sharma",
      serviceTitle: "Deep Cleaning",
      status: "accepted",
      bookingDate: "2026-04-10T10:30:00.000Z",
      timeSlot: "4:30 PM",
      amount: 3200,
      createdAt: "2026-04-09T08:10:00.000Z",
    },
    {
      id: "mock-client-provider-2",
      providerName: "Kabir Patel",
      serviceTitle: "AC Maintenance",
      status: "completed",
      bookingDate: "2026-04-05T08:30:00.000Z",
      timeSlot: "2:00 PM",
      amount: 1850,
      createdAt: "2026-04-07T11:15:00.000Z",
    },
    {
      id: "mock-client-provider-3",
      providerName: "Neha Verma",
      serviceTitle: "Home Tutor Visit",
      status: "completed",
      bookingDate: "2026-04-02T12:00:00.000Z",
      timeSlot: "6:00 PM",
      amount: 2400,
      createdAt: "2026-04-06T09:00:00.000Z",
    },
  ],
  activity7d: [
    { label: "Thu", count: 1 },
    { label: "Fri", count: 0 },
    { label: "Sat", count: 1 },
    { label: "Sun", count: 0 },
    { label: "Mon", count: 2 },
    { label: "Tue", count: 1 },
    { label: "Wed", count: 2 },
  ],
  upcomingMeetings: [
    {
      id: "mock-client-meeting-1",
      providerName: "Riya Sharma",
      serviceTitle: "Deep Cleaning",
      status: "accepted",
      bookingDate: "2026-04-10T10:30:00.000Z",
      timeSlot: "4:30 PM",
      amount: 3200,
      createdAt: "2026-04-09T08:10:00.000Z",
    },
    {
      id: "mock-client-meeting-2",
      providerName: "Kabir Patel",
      serviceTitle: "AC Maintenance",
      status: "pending",
      bookingDate: "2026-04-12T07:30:00.000Z",
      timeSlot: "1:00 PM",
      amount: 1850,
      createdAt: "2026-04-08T13:45:00.000Z",
    },
    {
      id: "mock-client-meeting-3",
      providerName: "Mohan Electric Works",
      serviceTitle: "Lighting Repair",
      status: "accepted",
      bookingDate: "2026-04-14T09:00:00.000Z",
      timeSlot: "11:00 AM",
      amount: 1400,
      createdAt: "2026-04-07T14:15:00.000Z",
    },
  ],
  currency: "INR",
};

export const mockProviderDashboard = {
  summary: {
    appointmentsBooked: 6,
    pendingRequests: 2,
    totalIncome: 27800,
    totalClients: 5,
  },
  earnings7d: [
    { label: "3 Apr", amount: 3200 },
    { label: "4 Apr", amount: 0 },
    { label: "5 Apr", amount: 4200 },
    { label: "6 Apr", amount: 3800 },
    { label: "7 Apr", amount: 0 },
    { label: "8 Apr", amount: 6200 },
    { label: "9 Apr", amount: 5400 },
  ],
  earnings6m: [
    { label: "Nov", amount: 8200 },
    { label: "Dec", amount: 11600 },
    { label: "Jan", amount: 14500 },
    { label: "Feb", amount: 18800 },
    { label: "Mar", amount: 23100 },
    { label: "Apr", amount: 27800 },
  ],
  todaySchedule: [
    {
      id: "mock-provider-schedule-1",
      clientName: "Aarav Mehta",
      serviceTitle: "Premium Home Cleaning",
      status: "accepted",
      bookingDate: "2026-04-09T08:00:00.000Z",
      timeSlot: "3:30 PM",
      amount: 4200,
      createdAt: "2026-04-09T06:40:00.000Z",
    },
    {
      id: "mock-provider-schedule-2",
      clientName: "Nisha Rao",
      serviceTitle: "Sofa and Carpet Care",
      status: "pending",
      bookingDate: "2026-04-09T12:00:00.000Z",
      timeSlot: "6:30 PM",
      amount: 2800,
      createdAt: "2026-04-08T12:15:00.000Z",
    },
  ],
  recentAppointments: [
    {
      id: "mock-provider-appointment-1",
      clientName: "Aarav Mehta",
      serviceTitle: "Premium Home Cleaning",
      status: "accepted",
      bookingDate: "2026-04-09T08:00:00.000Z",
      timeSlot: "3:30 PM",
      amount: 4200,
      createdAt: "2026-04-09T06:40:00.000Z",
    },
    {
      id: "mock-provider-appointment-2",
      clientName: "Nisha Rao",
      serviceTitle: "Sofa and Carpet Care",
      status: "pending",
      bookingDate: "2026-04-09T12:00:00.000Z",
      timeSlot: "6:30 PM",
      amount: 2800,
      createdAt: "2026-04-08T12:15:00.000Z",
    },
    {
      id: "mock-provider-appointment-3",
      clientName: "Dev Kapoor",
      serviceTitle: "Move-out Deep Cleaning",
      status: "completed",
      bookingDate: "2026-04-07T10:30:00.000Z",
      timeSlot: "2:00 PM",
      amount: 6100,
      createdAt: "2026-04-07T15:05:00.000Z",
    },
  ],
  topServices: shareFromMax([
    {
      serviceId: "mock-service-cleaning",
      serviceTitle: "Deep Cleaning",
      bookings: 8,
    },
    {
      serviceId: "mock-service-sofa",
      serviceTitle: "Sofa Care",
      bookings: 5,
    },
    {
      serviceId: "mock-service-kitchen",
      serviceTitle: "Kitchen Reset",
      bookings: 4,
    },
  ]),
  currency: "INR",
};

export const mockClientBookings = [
  {
    _id: "mock-booking-client-1",
    providerName: "Riya Sharma",
    providerId: {
      name: "Riya Sharma",
    },
    serviceTitle: "Deep Cleaning",
    serviceId: {
      title: "Deep Cleaning",
    },
    status: "accepted",
    bookingDate: "2026-04-10T10:30:00.000Z",
    timeSlot: "4:30 PM",
    price: 3200,
    paymentStatus: "paid",
    createdAt: "2026-04-09T08:10:00.000Z",
  },
  {
    _id: "mock-booking-client-2",
    providerName: "Kabir Patel",
    providerId: {
      name: "Kabir Patel",
    },
    serviceTitle: "AC Maintenance",
    serviceId: {
      title: "AC Maintenance",
    },
    status: "pending",
    bookingDate: "2026-04-12T07:30:00.000Z",
    timeSlot: "1:00 PM",
    price: 1850,
    paymentStatus: "pending",
    createdAt: "2026-04-08T13:45:00.000Z",
  },
  {
    _id: "mock-booking-client-3",
    providerName: "Neha Verma",
    providerId: {
      name: "Neha Verma",
    },
    serviceTitle: "Home Tutor Visit",
    serviceId: {
      title: "Home Tutor Visit",
    },
    status: "completed",
    bookingDate: "2026-04-05T15:00:00.000Z",
    timeSlot: "6:00 PM",
    price: 2400,
    paymentStatus: "paid",
    createdAt: "2026-04-06T09:00:00.000Z",
    review: {
      rating: 5,
      comment: "Very professional and punctual.",
    },
  },
];

export const mockProviderBookings = [
  {
    id: "mock-provider-booking-1",
    clientName: "Aarav Mehta",
    clientEmail: "aarav.sample@golocal.test",
    clientPhone: "+91 98100 11223",
    clientAddress: "Bandra West, Mumbai",
    clientPhoto: "",
    serviceTitle: "Premium Home Cleaning",
    serviceCategory: "Cleaning",
    bookingDate: "2026-04-10T10:30:00.000Z",
    timeSlot: "4:30 PM",
    status: "pending",
    price: 4200,
    createdAt: "2026-04-09T08:30:00.000Z",
  },
  {
    id: "mock-provider-booking-2",
    clientName: "Nisha Rao",
    clientEmail: "nisha.sample@golocal.test",
    clientPhone: "+91 98200 44556",
    clientAddress: "Andheri East, Mumbai",
    clientPhoto: "",
    serviceTitle: "Sofa and Carpet Care",
    serviceCategory: "Cleaning",
    bookingDate: "2026-04-09T12:00:00.000Z",
    timeSlot: "6:30 PM",
    status: "accepted",
    price: 2800,
    createdAt: "2026-04-08T12:15:00.000Z",
  },
  {
    id: "mock-provider-booking-3",
    clientName: "Dev Kapoor",
    clientEmail: "dev.sample@golocal.test",
    clientPhone: "+91 98989 33001",
    clientAddress: "Powai, Mumbai",
    clientPhoto: "",
    serviceTitle: "Move-out Deep Cleaning",
    serviceCategory: "Cleaning",
    bookingDate: "2026-04-07T10:30:00.000Z",
    timeSlot: "2:00 PM",
    status: "completed",
    price: 6100,
    createdAt: "2026-04-07T15:05:00.000Z",
  },
];

export const mockClientTransactions = [
  {
    id: "mock-client-transaction-1",
    invoiceNumber: "INV-MOCK-2001",
    transactionId: "TX-MOCK-2001",
    providerName: "Riya Sharma",
    providerServiceType: "Cleaning",
    serviceTitle: "Deep Cleaning",
    amount: 3200,
    totalPaidByClient: 3200,
    createdAt: "2026-04-09T08:10:00.000Z",
    paymentMethod: "upi",
    status: "paid",
  },
  {
    id: "mock-client-transaction-2",
    invoiceNumber: "INV-MOCK-2002",
    transactionId: "TX-MOCK-2002",
    providerName: "Kabir Patel",
    providerServiceType: "HVAC",
    serviceTitle: "AC Maintenance",
    amount: 1850,
    totalPaidByClient: 1850,
    createdAt: "2026-04-08T13:45:00.000Z",
    paymentMethod: "upi",
    status: "pending",
  },
  {
    id: "mock-client-transaction-3",
    invoiceNumber: "INV-MOCK-2003",
    transactionId: "TX-MOCK-2003",
    providerName: "Neha Verma",
    providerServiceType: "Education",
    serviceTitle: "Home Tutor Visit",
    amount: 2400,
    totalPaidByClient: 2400,
    createdAt: "2026-04-06T09:00:00.000Z",
    paymentMethod: "upi",
    status: "paid",
  },
];

export const mockProviderPayouts = [
  {
    id: "mock-provider-payout-1",
    serviceTitle: "Premium Home Cleaning",
    amount: 4200,
    commission: 420,
    netAmount: 3780,
    clientPaid: 4200,
    status: "paid",
    createdAt: "2026-04-09T08:30:00.000Z",
    providerUpiId: "riya@upi",
    providerBankName: "HDFC Bank",
    clientUpiId: "aarav@upi",
    clientBankName: "ICICI Bank",
  },
  {
    id: "mock-provider-payout-2",
    serviceTitle: "Sofa and Carpet Care",
    amount: 2800,
    commission: 280,
    netAmount: 2520,
    clientPaid: 2800,
    status: "pending",
    createdAt: "2026-04-08T12:15:00.000Z",
    providerUpiId: "riya@upi",
    providerBankName: "HDFC Bank",
    clientUpiId: "nisha@upi",
    clientBankName: "Axis Bank",
  },
  {
    id: "mock-provider-payout-3",
    serviceTitle: "Move-out Deep Cleaning",
    amount: 6100,
    commission: 610,
    netAmount: 5490,
    clientPaid: 6100,
    status: "paid",
    createdAt: "2026-04-07T15:05:00.000Z",
    providerUpiId: "riya@upi",
    providerBankName: "HDFC Bank",
    clientUpiId: "dev@upi",
    clientBankName: "SBI",
  },
];

export const mockDisputeThreads = {
  client: [
    {
      id: "mock-client-thread-1",
      threadKey: "mock-client-thread-1",
      threadTitle: "Riya Sharma",
      targetType: "provider",
      status: "under_review",
      latestAt: "2026-04-09T09:20:00.000Z",
      latestLabel: "9 Apr 2026, 2:50 PM",
      items: [
        {
          id: "mock-client-dispute-1",
          threadKey: "mock-client-thread-1",
          targetType: "provider",
          subject: "Missed arrival window",
          reason: "Late Arrival",
          description:
            "The provider confirmed the session but arrived more than an hour after the agreed slot.",
          status: "under_review",
          resolutionNote: "",
          createdAt: "2026-04-09T09:20:00.000Z",
          createdLabel: "9 Apr 2026, 2:50 PM",
          reporterName: "You",
          bookingLabel: "#CK4201",
          targetUserName: "Riya Sharma",
          roleLabel: "reported by you",
        },
      ],
    },
    {
      id: "mock-client-thread-2",
      threadKey: "mock-client-thread-2",
      threadTitle: "Website & Platform Support",
      targetType: "platform",
      status: "open",
      latestAt: "2026-04-08T07:40:00.000Z",
      latestLabel: "8 Apr 2026, 1:10 PM",
      items: [
        {
          id: "mock-client-dispute-2",
          threadKey: "mock-client-thread-2",
          targetType: "platform",
          subject: "Payment page timed out",
          reason: "Platform Bug",
          description:
            "Checkout timed out twice before the confirmation screen loaded.",
          status: "open",
          resolutionNote: "",
          createdAt: "2026-04-08T07:40:00.000Z",
          createdLabel: "8 Apr 2026, 1:10 PM",
          reporterName: "You",
          bookingLabel: "Platform",
          targetUserName: "Admin",
          roleLabel: "reported by you",
        },
      ],
    },
  ],
  provider: [
    {
      id: "mock-provider-thread-1",
      threadKey: "mock-provider-thread-1",
      threadTitle: "Aarav Mehta",
      targetType: "client",
      status: "open",
      latestAt: "2026-04-09T06:55:00.000Z",
      latestLabel: "9 Apr 2026, 12:25 PM",
      items: [
        {
          id: "mock-provider-dispute-1",
          threadKey: "mock-provider-thread-1",
          targetType: "client",
          subject: "Access instructions missing",
          reason: "Behavior Concern",
          description:
            "The booking notes did not include building access details, which delayed the appointment start.",
          status: "open",
          resolutionNote: "",
          createdAt: "2026-04-09T06:55:00.000Z",
          createdLabel: "9 Apr 2026, 12:25 PM",
          reporterName: "You",
          bookingLabel: "#PR1120",
          targetUserName: "Aarav Mehta",
          roleLabel: "reported by you",
        },
      ],
    },
  ],
};

export const mockDisputeBookings = {
  client: [
    {
      _id: "mock-dispute-booking-client-1",
      providerId: { name: "Riya Sharma" },
      serviceId: { title: "Deep Cleaning" },
      bookingDate: "2026-04-10T10:30:00.000Z",
      createdAt: "2026-04-09T08:10:00.000Z",
    },
    {
      _id: "mock-dispute-booking-client-2",
      providerId: { name: "Kabir Patel" },
      serviceId: { title: "AC Maintenance" },
      bookingDate: "2026-04-12T07:30:00.000Z",
      createdAt: "2026-04-08T13:45:00.000Z",
    },
  ],
  provider: [
    {
      _id: "mock-dispute-booking-provider-1",
      clientId: { name: "Aarav Mehta" },
      serviceId: { title: "Premium Home Cleaning" },
      bookingDate: "2026-04-10T10:30:00.000Z",
      createdAt: "2026-04-09T08:30:00.000Z",
    },
    {
      _id: "mock-dispute-booking-provider-2",
      clientId: { name: "Nisha Rao" },
      serviceId: { title: "Sofa and Carpet Care" },
      bookingDate: "2026-04-09T12:00:00.000Z",
      createdAt: "2026-04-08T12:15:00.000Z",
    },
  ],
};

export const mockAdminDashboard = {
  summary: {
    totalUsers: 14,
    pendingProviders: 3,
    revenue: 86400,
    bookingsTracked: 26,
    openDisputes: 4,
  },
  charts: {
    growth: [
      { month: "Nov", users: 2, revenue: 8400, bookings: 3 },
      { month: "Dec", users: 3, revenue: 12600, bookings: 4 },
      { month: "Jan", users: 2, revenue: 14100, bookings: 4 },
      { month: "Feb", users: 3, revenue: 17300, bookings: 5 },
      { month: "Mar", users: 2, revenue: 19800, bookings: 5 },
      { month: "Apr", users: 2, revenue: 14200, bookings: 5 },
    ],
    categoryDistribution: [
      { name: "Cleaning", value: 6 },
      { name: "Electrical", value: 3 },
      { name: "HVAC", value: 2 },
      { name: "Beauty", value: 2 },
      { name: "Tutoring", value: 1 },
    ],
  },
  meta: {
    currency: "INR",
  },
};

export const mockAdminUsers = [
  {
    id: "mock-admin-user-1",
    name: "Riya Sharma",
    email: "riya.sample@golocal.test",
    role: "provider",
    status: "active",
    approvalStatus: "approved",
    serviceType: "Cleaning",
    joinedAt: "2026-04-09T08:20:00.000Z",
  },
  {
    id: "mock-admin-user-2",
    name: "Kabir Patel",
    email: "kabir.sample@golocal.test",
    role: "provider",
    status: "pending",
    approvalStatus: "pending",
    serviceType: "HVAC",
    joinedAt: "2026-04-08T13:40:00.000Z",
  },
  {
    id: "mock-admin-user-3",
    name: "Arjun Mehta",
    email: "arjun.sample@golocal.test",
    role: "client",
    status: "active",
    approvalStatus: "approved",
    serviceType: "",
    joinedAt: "2026-04-07T09:10:00.000Z",
  },
];

export const mockAdminBookings = [
  {
    id: "mock-admin-booking-1",
    service: "Deep Cleaning",
    category: "Cleaning",
    client: "Arjun Mehta",
    clientEmail: "arjun.sample@golocal.test",
    provider: "Riya Sharma",
    providerEmail: "riya.sample@golocal.test",
    schedule: "4/10/2026, 4:30 PM",
    status: "accepted",
    paymentStatus: "paid",
    amountLabel: "INR 3,200",
    createdAt: "2026-04-09T08:10:00.000Z",
  },
  {
    id: "mock-admin-booking-2",
    service: "AC Maintenance",
    category: "HVAC",
    client: "Tanvi Gupta",
    clientEmail: "tanvi.sample@golocal.test",
    provider: "Kabir Patel",
    providerEmail: "kabir.sample@golocal.test",
    schedule: "4/12/2026, 1:00 PM",
    status: "pending",
    paymentStatus: "pending",
    amountLabel: "INR 1,850",
    createdAt: "2026-04-08T13:45:00.000Z",
  },
];

export const mockAdminTransactions = [
  {
    id: "mock-admin-transaction-1",
    reference: "TX-MOCK-3401",
    provider: "Riya Sharma",
    service: "Deep Cleaning",
    amountLabel: "INR 3,200",
    platformFeeLabel: "INR 320",
    status: "paid",
    statusLabel: "paid",
    createdLabel: "4/9/2026, 1:40 PM",
    createdAt: "2026-04-09T08:10:00.000Z",
  },
  {
    id: "mock-admin-transaction-2",
    reference: "TX-MOCK-3402",
    provider: "Kabir Patel",
    service: "AC Maintenance",
    amountLabel: "INR 1,850",
    platformFeeLabel: "INR 185",
    status: "pending",
    statusLabel: "pending",
    createdLabel: "4/8/2026, 7:15 PM",
    createdAt: "2026-04-08T13:45:00.000Z",
  },
];

export const mockAdminFinanceAlerts = [
  {
    id: "mock-finance-alert-1",
    title: "Sample payout review queue",
    description:
      "Two placeholder settlements are still pending so the finance layout stays populated during low traffic.",
    severity: "watchlist",
    createdAt: "2026-04-08T13:45:00.000Z",
  },
];

export const mockAdminDisputeThreads = [
  {
    id: "mock-admin-thread-1",
    threadKey: "mock-admin-thread-1",
    threadTitle: "Riya Sharma",
    targetType: "provider",
    status: "under_review",
    reporterName: "Arjun Mehta",
    targetUserName: "Riya Sharma",
    latestAt: "2026-04-09T09:20:00.000Z",
    latestLabel: "4/9/2026, 2:50 PM",
    items: [
      {
        id: "mock-admin-dispute-1",
        threadKey: "mock-admin-thread-1",
        threadTitle: "Riya Sharma",
        bookingLabel: "#CK4201",
        client: "Arjun Mehta",
        provider: "Riya Sharma",
        reporterName: "Arjun Mehta",
        targetUserName: "Riya Sharma",
        targetType: "provider",
        subject: "Missed arrival window",
        reason: "Late Arrival",
        description:
          "The provider confirmed the appointment but arrived significantly after the agreed time window.",
        status: "under_review",
        resolutionNote: "",
        createdAt: "2026-04-09T09:20:00.000Z",
        createdLabel: "4/9/2026, 2:50 PM",
      },
    ],
  },
  {
    id: "mock-admin-thread-2",
    threadKey: "mock-admin-thread-2",
    threadTitle: "Website support",
    targetType: "platform",
    status: "open",
    reporterName: "Nisha Rao",
    targetUserName: "Platform",
    latestAt: "2026-04-08T07:40:00.000Z",
    latestLabel: "4/8/2026, 1:10 PM",
    items: [
      {
        id: "mock-admin-dispute-2",
        threadKey: "mock-admin-thread-2",
        threadTitle: "Website support",
        bookingLabel: "Platform",
        client: "Nisha Rao",
        provider: "-",
        reporterName: "Nisha Rao",
        targetUserName: "Platform",
        targetType: "platform",
        subject: "Checkout timeout",
        reason: "Platform Bug",
        description:
          "Checkout timed out twice before the booking confirmation was generated.",
        status: "open",
        resolutionNote: "",
        createdAt: "2026-04-08T07:40:00.000Z",
        createdLabel: "4/8/2026, 1:10 PM",
      },
    ],
  },
];

export const mockClientProviders = [
  {
    id: "mock-provider-card-1",
    name: "Riya Sharma",
    serviceType: "Deep Cleaning Specialist",
    rating: 4.9,
    reviewCount: 48,
    location: "Bandra West, Mumbai",
    hourlyRate: 850,
    image: "",
    available: true,
    verified: true,
    completedJobs: 112,
    experience: 6,
    phone: "+91 98100 11223",
    email: "riya.sample@golocal.test",
    bio: "Residential cleaning professional focused on move-in and deep clean projects.",
    services: ["Deep Cleaning", "Move-out Cleaning", "Kitchen Reset"],
    availabilitySummary: {
      status: "available",
      reason: "Available for bookings this week.",
      canBook: true,
    },
    createdAt: "2026-04-09T08:00:00.000Z",
  },
  {
    id: "mock-provider-card-2",
    name: "Kabir Patel",
    serviceType: "AC Repair and Maintenance",
    rating: 4.7,
    reviewCount: 36,
    location: "Andheri East, Mumbai",
    hourlyRate: 950,
    image: "",
    available: true,
    verified: true,
    completedJobs: 84,
    experience: 5,
    phone: "+91 98200 44556",
    email: "kabir.sample@golocal.test",
    bio: "Reliable HVAC technician for annual maintenance and emergency cooling issues.",
    services: ["AC Maintenance", "Gas Refill", "Filter Cleaning"],
    availabilitySummary: {
      status: "available",
      reason: "Two slots are open this weekend.",
      canBook: true,
    },
    createdAt: "2026-04-08T13:30:00.000Z",
  },
];

export const mockClientNotifications = [
  {
    id: "mock-client-notification-1",
    title: "Sample booking confirmed",
    message: "A sample provider accepted your Deep Cleaning request for Friday.",
    type: "booking",
    read: false,
    createdAt: "2026-04-09T08:20:00.000Z",
  },
  {
    id: "mock-client-notification-2",
    title: "Sample payment receipt",
    message: "Sample invoice INV-MOCK-2001 is ready to review or export.",
    type: "payment",
    read: true,
    createdAt: "2026-04-08T13:50:00.000Z",
  },
];

export const mockProviderNotifications = [
  {
    id: "mock-provider-notification-1",
    title: "Sample booking request",
    message: "Aarav Mehta requested a Premium Home Cleaning session.",
    type: "booking",
    read: false,
    createdAt: "2026-04-09T08:30:00.000Z",
  },
  {
    id: "mock-provider-notification-2",
    title: "Sample payout update",
    message: "One sample settlement is still pending review in your earnings center.",
    type: "payment",
    read: true,
    createdAt: "2026-04-08T12:20:00.000Z",
  },
];
