const mongoose = require("mongoose");
const path = require("path");
require("dotenv").config({ path: path.join(__dirname, "../../.env") });

const User = require("../models/User");

const MOCK_PROVIDERS = [
  {
    email: "mock1@provider.com",
    name: "John Doe (Demo)",
    role: "provider",
    password: "password123",
    phone: "1112223301",
    serviceType: "Plumbing",
    location: "New York",
    address: "123 Plumbing St. NY",
    hourlyRate: 50,
    experience: 5,
    bio: "Experienced plumber fixing leaks all over the city. I love helping out people. (This is a mock provider).",
    workCategories: ["Pipe Repair", "Installation"],
    isMock: true,
    isVerified: true,
    approvalStatus: "approved",
    status: "active",
    availability: true,
    profileImage: "https://i.pravatar.cc/150?u=mock1",
    bankName: "Chase",
    accountNumber: "12345601",
    accountHolderName: "John Doe",
  },
  {
    email: "mock2@provider.com",
    name: "Alice Smith (Demo)",
    role: "provider",
    password: "password123",
    phone: "1112223302",
    serviceType: "Electrical",
    location: "Los Angeles",
    address: "456 Electric Ave. LA",
    hourlyRate: 70,
    experience: 8,
    bio: "Licensed electrician dealing with wiring and fixtures. (This is a mock provider).",
    workCategories: ["Wiring", "Troubleshooting"],
    isMock: true,
    isVerified: true,
    approvalStatus: "approved",
    status: "active",
    availability: true,
    profileImage: "https://i.pravatar.cc/150?u=mock2",
    bankName: "BofA",
    accountNumber: "12345602",
    accountHolderName: "Alice Smith",
  },
  {
    email: "mock3@provider.com",
    name: "Bob Builder (Demo)",
    role: "provider",
    password: "password123",
    phone: "1112223303",
    serviceType: "Carpentry",
    location: "Chicago",
    address: "789 Wood St. CHI",
    hourlyRate: 60,
    experience: 4,
    bio: "Can build it. Yes I can. Furniture assembly and custom woodworking. (This is a mock provider).",
    workCategories: ["Furniture", "Repair"],
    isMock: true,
    isVerified: true,
    approvalStatus: "approved",
    status: "active",
    availability: true,
    profileImage: "https://i.pravatar.cc/150?u=mock3",
    bankName: "Wells Fargo",
    accountNumber: "12345603",
    accountHolderName: "Bob Builder",
  },
  {
    email: "mock4@provider.com",
    name: "Sarah Painter (Demo)",
    role: "provider",
    password: "password123",
    phone: "1112223304",
    serviceType: "Painting",
    location: "Houston",
    address: "101 Color Rd. HOU",
    hourlyRate: 40,
    experience: 6,
    bio: "Adding color to your walls with precision and care. (This is a mock provider).",
    workCategories: ["Interior", "Exterior"],
    isMock: true,
    isVerified: true,
    approvalStatus: "approved",
    status: "active",
    availability: true,
    profileImage: "https://i.pravatar.cc/150?u=mock4",
    bankName: "Chase",
    accountNumber: "12345604",
    accountHolderName: "Sarah Painter",
  },
  {
    email: "mock5@provider.com",
    name: "Mike Clear (Demo)",
    role: "provider",
    password: "password123",
    phone: "1112223305",
    serviceType: "Cleaning",
    location: "Phoenix",
    address: "202 Dust Blvd. PHX",
    hourlyRate: 35,
    experience: 3,
    bio: "Deep cleaning services for your home and office. (This is a mock provider).",
    workCategories: ["Deep Clean", "Carpet"],
    isMock: true,
    isVerified: true,
    approvalStatus: "approved",
    status: "active",
    availability: true,
    profileImage: "https://i.pravatar.cc/150?u=mock5",
    bankName: "BofA",
    accountNumber: "12345605",
    accountHolderName: "Mike Clear",
  },
  {
    email: "mock6@provider.com",
    name: "Tom Cool (Demo)",
    role: "provider",
    password: "password123",
    phone: "1112223306",
    serviceType: "AC Repair",
    location: "Miami",
    address: "303 Ice Ave. MIA",
    hourlyRate: 80,
    experience: 10,
    bio: "Keeping you cool in the summer heat. AC repair and maintenance. (This is a mock provider).",
    workCategories: ["Repair", "Maintenance"],
    isMock: true,
    isVerified: true,
    approvalStatus: "approved",
    status: "active",
    availability: true,
    profileImage: "https://i.pravatar.cc/150?u=mock6",
    bankName: "Citi",
    accountNumber: "12345606",
    accountHolderName: "Tom Cool",
  },
  {
    email: "mock7@provider.com",
    name: "Emma Fixit (Demo)",
    role: "provider",
    password: "password123",
    phone: "1112223307",
    serviceType: "Appliance Repair",
    location: "Dallas",
    address: "404 Gear St. DAL",
    hourlyRate: 65,
    experience: 7,
    bio: "Fixing your washing machines, fridges, and more. (This is a mock provider).",
    workCategories: ["Kitchen", "Laundry"],
    isMock: true,
    isVerified: true,
    approvalStatus: "approved",
    status: "active",
    availability: true,
    profileImage: "https://i.pravatar.cc/150?u=mock7",
    bankName: "Chase",
    accountNumber: "12345607",
    accountHolderName: "Emma Fixit",
  },
  {
    email: "mock8@provider.com",
    name: "Leo Mover (Demo)",
    role: "provider",
    password: "password123",
    phone: "1112223308",
    serviceType: "Moving",
    location: "Atlanta",
    address: "505 Lift Way ATL",
    hourlyRate: 90,
    experience: 5,
    bio: "Fast and reliable moving service. We pack and move everything. (This is a mock provider).",
    workCategories: ["Local Move", "Packing"],
    isMock: true,
    isVerified: true,
    approvalStatus: "approved",
    status: "active",
    availability: true,
    profileImage: "https://i.pravatar.cc/150?u=mock8",
    bankName: "Wells Fargo",
    accountNumber: "12345608",
    accountHolderName: "Leo Mover",
  },
  {
    email: "mock9@provider.com",
    name: "Nina Decor (Demo)",
    role: "provider",
    password: "password123",
    phone: "1112223309",
    serviceType: "Other",
    location: "Seattle",
    address: "606 Art Dr. SEA",
    hourlyRate: 55,
    experience: 4,
    bio: "Interior decoration and staging. Making your space beautiful. (This is a mock provider).",
    workCategories: ["Design", "Arrangement"],
    isMock: true,
    isVerified: true,
    approvalStatus: "approved",
    status: "active",
    availability: true,
    profileImage: "https://i.pravatar.cc/150?u=mock9",
    bankName: "Chase",
    accountNumber: "12345609",
    accountHolderName: "Nina Decor",
  },
  {
    email: "mock10@provider.com",
    name: "Sam Green (Demo)",
    role: "provider",
    password: "password123",
    phone: "1112223310",
    serviceType: "Other",
    location: "Denver",
    address: "707 Plant Rd. DEN",
    hourlyRate: 45,
    experience: 9,
    bio: "Gardening and landscaping services. (This is a mock provider).",
    workCategories: ["Lawn Care", "Planting"],
    isMock: true,
    isVerified: true,
    approvalStatus: "approved",
    status: "active",
    availability: true,
    profileImage: "https://i.pravatar.cc/150?u=mock10",
    bankName: "BofA",
    accountNumber: "12345610",
    accountHolderName: "Sam Green",
  }
];

async function insertMockProviders() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("Connected to MongoDB.");

    await User.deleteMany({ isMock: true });
    console.log("Cleared existing mock providers.");

    for (const provider of MOCK_PROVIDERS) {
      const user = new User(provider);
      user.verification = { status: "verified" };
      await user.save();
    }

    console.log("Inserted 10 mock providers successfully.");
  } catch (error) {
    console.error("Error inserting mock providers:", error);
  } finally {
    mongoose.disconnect();
  }
}

insertMockProviders();
